import Image from "next/image";
import logo from "../public/assets/shared/logo.svg";
import type { Metadata } from "next";
import { Bellefair, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import bkgHome from "../public/assets/home/background-home-desktop.jpg";
import Nav from "../components/Nav";

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bellefair",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["200", "400"],
  variable: "--font-barlow-condensed",
});

const barlow_condensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Space Tourism Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bellefair.variable} ${barlow.variable} ${barlow_condensed.variable}`}
    >
      <body className="relative max-w-[1440px] mx-auto border grid grid-rows-[min-content,auto] min-h-screen">
        <Image
          src={bkgHome}
          alt="background"
          className="fixed top-0 -z-10 min-w-max h-auto"
        />
        <header className="flex p-8 pr-0 pl-12 items-center">
          <Image src={logo} alt="logo" />
          <div className="h-[1px] bg-white opacity-30 w-full ml-8"></div>
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
