import type { Metadata } from "next";
import { Bellefair, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Nav from "../components/MainNav";
import Logo from "@/components/Logo";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Footer from "@/components/Footer";

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bellefair",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["200", "400"],
  variable: "--font-barlow",
});

const barlow_condensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Space Tourism Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bellefair.variable} ${barlow.variable} ${barlow_condensed.variable}`}
    >
      <body className="relative max-w-[1440px] mx-auto grid grid-rows-[min-content,auto] min-h-screen ">
        <header className="flex p-8 pr-0 pl-12 items-center z-20 relative">
          <Logo />
          <div className="h-[1px] bg-white opacity-30 w-full ml-8 max-sm:hidden"></div>
          <Nav />
        </header>
        <div className="z-10 grid">{children}</div>
        <SpeedInsights />
        <Footer />
      </body>
    </html>
  );
}
