import type { Metadata } from "next";
import { Bellefair, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bellefair",
});

const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["200", "400"],
  variable: "--font-barlow-condensed",
});

const barlow_condensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Space Tourism Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bellefair.variable} ${barlow.variable} ${barlow_condensed.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
